### PR TITLE
MSU-1

### PR DESCRIPTION
**Pull request by kylophone**
Got this working in BSNES, but I just tried it on my SD2SNES and it wasn't working, so it needs a little debugging still. You'll need `ffmpeg` installed on your machine to build the example (`make msu && make`). Feel free to clean up whatever.

### CODE REVIEW

**Comment by kylophone** [comment]
As far as I can tell this is the "official" MSU-1 doc: http://helmet.kafuka.org/msu1.htm

**Comment by Optiroc** [comment]
Thanks! I'll pull it as-is for now and make it work on SD2SNES when I get my SNES hooked up again (which should happen fairly soon since I have some quite interesting testing coming up!).

**Comment by kylophone** [comment]
@qwertymodo, any clue why this would work in BSNES but not on an SD2SNES? (Sorry about the random ping, but you seem to know the MSU stuff well).

**Comment by qwertymodo** [comment]
SD2SNES/Snes9x require a file named romname.msu1 in the same folder in order to signify that the MSU-1 is in use, otherwise it won't enable it (higan calls the same file msu1.rom). Also, the .pcm files should be named romname-#.pcm, with no extra leading digits in the track number, e.g. romname-1.pcm, not -01. If that still doesn't work, I can look into it some more and figure out what you're doing.

**Comment by kylophone** [comment]
@qwertymodo Yep. All of that stuff should be set. It seems like my SD2SNES is detecting the MSU-1, but failing to play back the audio. If you have a second, it'd be awesome if you could take a quick look. I wish the documentation for the MSU-1 wasn't so sparse...

**Comment by qwertymodo** [comment]
I don't currently have a system available that can easily build this, can you send me an assembled .sfc file?  I can provide my own .pcm files.  Either attaching here or emailing me to my username at gmail would probably be easiest.

**Comment by kylophone** [comment]
@qwertymodo Attached here. Thanks for looking at it!
[MSU1_libsfx.zip](https://github.com/Optiroc/libSFX/files/1374041/MSU1_libsfx.zip)

**Comment by qwertymodo** [comment]
Well, your ROM completely crashes bsnes-plus.  Here's as far as the tracelog gets

```
00837f sei                    A:0000 X:0000 Y:0000 S:01ff D:0000 DB:00 nv1BdIzc V:  0 H: 46 F: 0
008380 clc                    A:0000 X:0000 Y:0000 S:01ff D:0000 DB:00 nv1BdIzc V:  0 H: 50 F: 0
008381 xce                    A:0000 X:0000 Y:0000 S:01ff D:0000 DB:00 nv1BdIzc V:  0 H: 53 F: 0
008382 jml $808386   [808386] A:0000 X:0000 Y:0000 S:01ff D:0000 DB:00 nvMXdIzC V:  0 H: 57 F: 0
808386 lda #$01               A:0000 X:0000 Y:0000 S:01ff D:0000 DB:00 nvMXdIzC V:  0 H: 65 F: 0
808388 sta $420d     [00420d] A:0001 X:0000 Y:0000 S:01ff D:0000 DB:00 nvMXdIzC V:  0 H: 69 F: 0
80838b rep #$30               A:0001 X:0000 Y:0000 S:01ff D:0000 DB:00 nvMXdIzC V:  0 H: 76 F: 0
80838d ldx #$1fff             A:0001 X:0000 Y:0000 S:01ff D:0000 DB:00 nvmxdIzC V:  0 H: 81 F: 0
808390 txs                    A:0001 X:1fff Y:0000 S:01ff D:0000 DB:00 nvmxdIzC V:  0 H: 85 F: 0
808391 lda #$0000             A:0001 X:1fff Y:0000 S:1fff D:0000 DB:00 nvmxdIzC V:  0 H: 88 F: 0
808394 tcd                    A:0000 X:1fff Y:0000 S:1fff D:0000 DB:00 nvmxdIZC V:  0 H: 93 F: 0
808395 sep #$20               A:0000 X:1fff Y:0000 S:1fff D:0000 DB:00 nvmxdIZC V:  0 H: 96 F: 0
808397 phk                    A:0000 X:1fff Y:0000 S:1fff D:0000 DB:00 nvMxdIZC V:  0 H:100 F: 0
808398 plb                    A:0000 X:1fff Y:0000 S:1ffe D:0000 DB:00 nvMxdIZC V:  0 H:105 F: 0
808399 ldx #$0002             A:0000 X:1fff Y:0000 S:1fff D:0000 DB:80 NvMxdIzC V:  0 H:112 F: 0
80839c jsl $808251   [808251] A:0000 X:0002 Y:0000 S:1fff D:0000 DB:80 nvMxdIzC V:  0 H:116 F: 0
808251 lda $4212     [804212] A:0000 X:0002 Y:0000 S:1ffc D:0000 DB:80 nvMxdIzC V:  0 H:130 F: 0
```

So, right off the bat, I would highly suggest initializing all of the important system registers immediately, before doing anything else.  There are a couple of good examples here:
https://en.wikibooks.org/wiki/Super_NES_Programming/Initialization_Tutorial/Snes_Init

and here:
https://github.com/pinobatch/lorom-template/blob/master/src/init.s

You should just be able to copy one or the other verbatim.  Also, here is the SPC code I use to unmute the DSP:

http://forums.nesdev.com/viewtopic.php?p=181017#p181017

notice the echo channels are muted, and instead of sleeping, I return to the IPLROM.  Previously, I had terminated my SPC code with a bra #$FE loop, but that crashed bsnes-plus similarly to what I'm seeing here.

Give those a try and if it still doesn't work I can take another look.

**Comment by kylophone** [comment]
@qwertymodo This is good information. Thanks for taking the time to have a look! This should give me enough breadcrumbs for troubleshooting.

**Comment by Optiroc** [comment]
@qwertymodo What build of bsnes+ are you running? It's rather curious that it crashes at that, completely benign, instruction. An infinite loop on the SPC700 shouldn't bring the emulator down, either.

**Comment by Optiroc** [comment]
@kylophone Do you get a green or red screen on real hardware, btw?

**Comment by mrehkopf** [comment]
@Optiroc I don't think it really crashes at that particular instruction. I suspect that it crashes before being able to flush out the final part of the trace to disk. So the crash might occur a couple of instructions later.
Emulators seem especially crash happy when the stack pointer wraps so it might be worth paying attention to that ;)

**Comment by qwertymodo** [comment]
Yeah, I didn't mean to imply that the crash was related to that exact instruction, just that it occurred very early in the execution. It was also far enough in that I could tell that you weren't doing a lot of initialization. This is the latest public release of bsnes-plus... I think 3a?  Chances are, the actual hardware probably isn't crashing, but until I can get a trace log in the debugger, I can't really see what's happening when it reaches the MSU-1 code. Also, the screen is green on the SD2SNES.

**Comment by mrehkopf** [comment]
Assuming it happens very early: stepping manually isn't an option? ;)

**Comment by qwertymodo** [comment]
That IS stepped manually. That's the only way I could get that much. Clicking step one more time crashes the emulator.

**Comment by kylophone** [comment]
@qwertymodo I'm pretty sure your crash has to with the SPC700 instruction `sleep`. I seem to remember I once had a version of BSNES that did the same thing with both `sleep` and `stop`. I've pushed a fix to my `MSU` branch and attached a new rom [here](https://github.com/Optiroc/libSFX/files/1376591/msu1.zip). Both roms work fine in my BSNES+ (v073+ba).

@Optiroc MSU-1 is detected with the SD2SNES, and the screen is green. I can also tell the SNES hasn't crashed because the yellow LED briefly flashes (no audio, though) when I try to switch between the two tracks with the shoulder buttons. The yellow LED should be constant when playing back audio. I also thought it might be my SD card, but I can get other MSU-1 roms working on the same card. 

@mrehkopf Do you see any obvious reason why this isn't working on my SD2SNES but other MSU-1 roms are?

**Comment by qwertymodo** [comment]
Found the problem.  After you write the track number to $2004:5, you need to read $2000 until the audio busy flag clears, and then check to make sure the track missing flag is clear, and only THEN can you write to $2007.  The reason it works on emulators is that they can stall emulation until the audio is ready, so as far as the code can tell, it's immediately ready.  The SD2SNES actually has to seek the card and fill its buffer, so your write to $2007 fails because the audio isn't ready yet.

```
PlayTrack:
        sty     MSU_TRACK
@bsy:   lda     MSU_STATUS
        bit     #$40
        bne     @bsy
        lda     MSU_STATUS
        bit     #$08
        bne     @ret
        lda     #$03
        sta     MSU_CONTROL
@ret:   rts
```

**Comment by qwertymodo** [comment]
```
PlayTrack:
        sty     MSU_TRACK
@bsy: lda     MSU_STATUS
        bit     #$40
        bne     @bsy
        lda     MSU_STATUS
        bit     #$08
        bne     @ret
        lda     #$03
        sta     MSU_CONTROL
@ret:   rts
```

**Comment by kylophone** [comment]
Thanks! That makes sense. I'll give this a try when I get home tonight!

**Comment by kylophone** [comment]
@qwertymodo Yeah, that totally fixed it. I had coded up something similar when I was working on this last week, but I deleted it since I figured it wasn't necessary. Also, it didn't help that the kafuka doc doesn't bother checking `MSU_STATUS` when playing back audio either. I've added a commit to fix the issue and gave you authorship. Thanks again!

@Optiroc I went ahead and just pushed the fix to your branch. Hope that's OK!

**Comment by qwertymodo** [comment]
If you ever do a video demo, you'll need a similar data busy check any time you seek.

**Pull request merged**
